# SPDX-License-Identifier: GPL-2.0-or-later
# Minimal public-header/library discovery for the optional ModernQGIS bridge.
set(_QGIS_HINTS)
if(QGIS_PREFIX_PATH)
    list(APPEND _QGIS_HINTS "${QGIS_PREFIX_PATH}")
endif()
if(DEFINED ENV{QGIS_PREFIX_PATH})
    list(APPEND _QGIS_HINTS "$ENV{QGIS_PREFIX_PATH}")
endif()
if(DEFINED ENV{OSGEO4W_ROOT})
    list(APPEND _QGIS_HINTS "$ENV{OSGEO4W_ROOT}/apps/qgis" "$ENV{OSGEO4W_ROOT}/apps/qgis-ltr")
endif()
find_path(QGIS_INCLUDE_DIR NAMES qgis.h qgsapplication.h HINTS ${_QGIS_HINTS} PATH_SUFFIXES include include/qgis)
find_library(QGIS_CORE_LIBRARY NAMES qgis_core HINTS ${_QGIS_HINTS} PATH_SUFFIXES lib bin)
find_library(QGIS_GUI_LIBRARY NAMES qgis_gui HINTS ${_QGIS_HINTS} PATH_SUFFIXES lib bin)
set(QGIS_VERSION "")
if(QGIS_INCLUDE_DIR)
    foreach(_candidate qgsconfig.h qgis.h)
        if(EXISTS "${QGIS_INCLUDE_DIR}/${_candidate}")
            file(STRINGS "${QGIS_INCLUDE_DIR}/${_candidate}" _qgis_version_lines REGEX "(VERSION|QGIS_VERSION).*[0-9]+\\.[0-9]+")
            if(_qgis_version_lines)
                string(REGEX MATCH "[0-9]+\\.[0-9]+(\\.[0-9]+)?" QGIS_VERSION "${_qgis_version_lines}")
                if(QGIS_VERSION)
                    break()
                endif()
            endif()
        endif()
    endforeach()
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(QGIS REQUIRED_VARS QGIS_INCLUDE_DIR QGIS_CORE_LIBRARY QGIS_GUI_LIBRARY VERSION_VAR QGIS_VERSION)
if(QGIS_FOUND AND NOT TARGET QGIS::Core)
    add_library(QGIS::Core UNKNOWN IMPORTED)
    set_target_properties(QGIS::Core PROPERTIES IMPORTED_LOCATION "${QGIS_CORE_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${QGIS_INCLUDE_DIR}")
endif()
if(QGIS_FOUND AND NOT TARGET QGIS::Gui)
    add_library(QGIS::Gui UNKNOWN IMPORTED)
    set_target_properties(QGIS::Gui PROPERTIES IMPORTED_LOCATION "${QGIS_GUI_LIBRARY}" INTERFACE_INCLUDE_DIRECTORIES "${QGIS_INCLUDE_DIR}" INTERFACE_LINK_LIBRARIES QGIS::Core)
endif()
mark_as_advanced(QGIS_INCLUDE_DIR QGIS_CORE_LIBRARY QGIS_GUI_LIBRARY)
